#!/bin/bash

UNAME=sim
IMGNAME=sim-runtime

xhost +SI:localuser:$USER

if [ -z "${NAME}" ]; then
    NAME="${IMGNAME}-container"
fi
echo "Image name: $IMGNAME"
echo "Container name: $NAME"

if [ -z ${XDG_RUNTIME_DIR+x} ]; then
    export XDG_RUNTIME_DIR=/run/user/$(id -u)
fi

if [ -z "${XAUTHORITY}" ]; then
    if [ -f "${HOME}/.Xauthority" ]; then
        export XAUTHORITY="${HOME}/.Xauthority"
    else
        export XAUTHORITY="/run/user/$(id -u)/gdm/Xauthority"
    fi
    echo "\$XAUTHORITY was not set.  Defaulting to ${XAUTHORITY}"
fi

if [ -f /usr/share/icons/default/index.theme ]; then
    CURSOR_THEME=/usr/share/icons/default/index.theme
elif [ -f ${HOME}/.icons/default/index.theme ]; then
    CURSOR_THEME=${HOME}/.icons/default/index.theme
elif [ -f /etc/alternatives/x-cursor-theme ]; then
    CURSOR_THEME=/etc/alternatives/x-cursor-theme
else
    unset CURSOR_THEME
fi

if ! [ -z "${CURSOR_THEME}" ]; then
    export MOUNT_CURSOR_THEME=(--mount type=bind,source=${CURSOR_THEME},target=/usr/share/icons/default/index.theme,readonly)
fi

if [ -z "$(docker images -q $IMGNAME 2> /dev/null)" ]; then
  docker build -t $IMGNAME .
fi

if [ -z "$(docker ps -a | grep $NAME)" ]; then
    docker run -it \
        --net=host \
        --privileged \
        --user "$(id -u)" \
        --name "$NAME" \
        --security-opt=label=disable \
        --env DISPLAY=${DISPLAY} \
        --env PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native \
        --env PULSE_COOKIE=/run/pulse/cookie \
        --env QT_AUTO_SCREEN_SCALE_FACTOR=1 \
        --env XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR} \
        --volume $(pwd):/home/${UNAME}/volumed_ws/ \
        --volume /tmp/.X11-unix:/tmp/.X11-unix \
        --volume ~/.Xauthority:/home/${UNAME}/.Xauthority \
        --device /dev/dri \
        --device /dev/input \
        --device /dev/nvidia0 \
        --device /dev/nvidiactl \
        --device /dev/nvidia-modeset \
        --device /dev/nvidia-uvm \
        --device /dev/nvidia-uvm-tools \
        --device /dev/bus/usb \
        --mount type=bind,source=${XDG_RUNTIME_DIR}/pipewire-0,target=${XDG_RUNTIME_DIR}/pipewire-0 \
        --mount type=bind,source=$XAUTHORITY,target=/tmp/.host_Xauthority,readonly \
        --mount type=bind,source=/etc/localtime,target=/etc/localtime,readonly \
        --mount type=bind,source=${XDG_RUNTIME_DIR}/pulse/native,target=${XDG_RUNTIME_DIR}/pulse/native \
        --mount type=bind,source=${HOME}/.config/pulse/cookie,target=/run/pulse/cookie \
        --mount type=bind,source=${HOME}/.local/share/fonts,target=/usr/share/fonts,readonly \
        --mount type=bind,source=/usr/share/fonts,target=/home/${UNAME}/.local/share/fonts \
        "${MOUNT_CURSOR_THEME[@]}" \
        "$IMGNAME" bash
else
    docker start -i "$NAME"
fi

xhost -
